########################################################################
# Import this file in your application.yml.
# Then activate "actuator" or "actuator-expose-all" profile.
#
# For more endpoints, see:
#   https://docs.spring.io/spring-boot/reference/actuator/endpoints.html
########################################################################

### For production ###
spring:
  config:
    activate:
      on-profile: actuator

management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include:
          - health
          - heapdump
          - threaddump
          - metrics

---

### For development ###
spring:
  config:
    activate:
      on-profile: actuator-expose-all

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

---

### Default ###
spring:
  config:
    activate:
      on-profile: actuator | actuator-expose-all

management:
  endpoint:
    health:
      probes:
        enabled: true
