spring:
  application:
    name: "actuator"
  main:
    banner-mode: off
  output:
    ansi:
      enabled: detect
  lifecycle:
    timeout-per-shutdown-phase: 10s

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  config:
    activate:
      on-profile: "prod"

management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        # See: https://docs.spring.io/spring-boot/reference/actuator/endpoints.html
        include:
          - "health"
          - "heapdump"
