spring:
  application:
    name: "jpa-h2"
  # Activate "development" profile group by default.
  # Use "--spring.profiles.active=production" to activate "production" profile group.
  profiles:
    active: development

---

### Import and group profiles ###
spring:
  config:
    import:
      - classpath:configs/h2.yml
  profiles:
    group:
      production:
      development:
        - h2-memory
        # or h2-file

---

### Other configs ###
spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: detect
  lifecycle:
    timeout-per-shutdown-phase: 10s

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

logging:
  level:
    root: info