spring:
  application:
    name: "template"
  main:
    banner-mode: off
  output:
    ansi:
      enabled: detect
  lifecycle:
    timeout-per-shutdown-phase: 10s

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
