spring:
  application:
    name: "logback"

logging:
  file:
    name: "logs/${spring.application.name}/recent.log"
  level:
    root: info
  logback:
    rollingpolicy:
      file-name-pattern: "logs/${spring.application.name}/%d{yyyy-MM-dd}.%i.log"
      max-file-size: 10MB
      max-history: 30
