spring:
  application:
    name: "logback"
  main:
    banner-mode: off
  output:
    ansi:
      enabled: detect
  lifecycle:
    timeout-per-shutdown-phase: 10s

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

logging:
  file:
    name: "logs/${spring.application.name}/recent.log"
  level:
    root: info
  logback:
    rollingpolicy:
      file-name-pattern: "logs/${spring.application.name}/%d{yyyy-MM-dd}.%i.log"
      max-file-size: 10MB
      max-history: 30
