spring:
  application:
    name: "logback"
  # Activate "development" profile group by default.
  # Use "--spring.profiles.active=production" to activate "production" profile group.
  profiles:
    active: development

---

### Import and group profiles ###
spring:
  config:
    import:
      - classpath:configs/logback.yml
  profiles:
    group:
      production:
        - logback
      development:
      # activate "logback" profile if needed

---

### Other configs ###
spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: detect
  lifecycle:
    timeout-per-shutdown-phase: 10s

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

logging:
  level:
    root: info
